### ISSUE TITLE
[0.0.3] Changes TODO in the update

### ISSUE THREAD

**Issue by NicolasOmar** [NicolasOmar/my-budget-react#5]
- [ ] Calling setState multiple times is not convenient. If the await stops the execution of this function this is ok.
- [ ] Another option is to save the user in the variable. Be sure to not remove values that are already in the user. Remember that the idea is to avoid re-rendering and recheck between the dom and shadow dom
- [ ] Suggestion: Using maps

**Comment by NicolasOmar** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Solve issues before v0.1.0](https://trello.com/c/GhnopU75/55-solve-issues-before-v010)
